### ISSUE TITLE
Issue in the submitted 2.5.0 packages

### ISSUE THREAD

**Issue by boris-kolpackov** [build2-packaging/imgui-sfml#1]
The `buildfile` has `-DIMGUI_IMPL_EXPORT` which feels iffy to me. I haven't dug very deep, but this macro controls `dllexport`/`dllimport` in `imconfig.h`. Normally, such macros should only be defined when building the library itself, and not libraries that use the library. Also looks like this library has its own macro (`IMGUI_SFML_EXPORTS`). I think currently this is harmless (because this macro is not used anywhere in the source code and no other backend that uses it is linked) but probably good idea to cleanup.

**Comment by Rookfighter** [comment]
You are right, I guess this was a copy and paste mistake (the other imgui backends use this macro). Will fix it in a new revision.
